import type { Metadata } from "next";
import { Libre_Franklin } from "next/font/google";
import "./globals.css";

const libre = Libre_Franklin({
  variable: "--font-libre-franklin",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${libre.variable} ${libre.className} antialiased`} suppressHydrationWarning={true}
      >
        {children}
      </body>
    </html>
  );
}
